services:
  sequencer:
    image: consensys/linea-besu-package:devnet-395ec6d # check plugins when updating f2ff06c or higher
    profiles: [ "nodes", "services" ]
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8550:8550"
      - "19545:9545"
      - "30301:30301"
      - "30305:30303"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /tmp/pid ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    restart: "no"
    environment:
      LOG4J_CONFIGURATION_FILE: /var/lib/besu/log4j.xml
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:-UseG1GC -XX:+UseZGC -Xmx20g -Xss64m
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/config.toml \
        --nat-method="AUTO" \
        --node-private-key-file="/var/lib/besu/key" \
        --plugin-linea-l1-polling-interval="PT12S" \
        --plugin-linea-l1-smart-contract-address="0x47a64E68563E8e39930391835ab9BE1C0c3Cdb80" \
        --plugin-linea-l1-rpc-endpoint="http://192.168.1.201:8545" \
        --plugin-linea-rejected-tx-endpoint="http://transaction-exclusion-api:8080" \
        --plugin-linea-node-type="SEQUENCER"
    volumes:
      - ./config/sequencer/config.toml:/var/lib/besu/config.toml:ro
      - ./config/sequencer/denylist.txt:/var/lib/besu/denylist.txt:ro
      - ./config/genesis/genesis.devnet.json:/var/lib/besu/genesis.json:ro
      - ./config/sequencer/key:/var/lib/besu/key
      - ./config/sequencer/log4j.xml:/var/lib/besu/log4j.xml:ro
      - ./config/sequencer/traces-limits-v2.toml:/var/lib/besu/traces-limits-v2.toml:ro
      - sequencer-data:/opt/besu
    networks:
      devnet:
        ipv4_address: 10.42.0.12

  l2-node:
    image: consensys/linea-geth:${ZKGETH_TAG:-0588665}
    platform: linux/amd64
    profiles: [ "nodes", "services" ]
    depends_on:
      sequencer:
        condition: service_healthy
    ports:
      - "8845:8545"
      - "8846:8546"
      - "30306:30303"
    environment:
      DATA_DIR: "/data"
      BOOTNODES: "enode://94b0eebcac4ffa2946a038bcf3e3155db348945231947432cb5cf2611bfab3864f154387962bf90a7b52fbc0c58498d43a58e44d4ce00f8b7b6883733fffee4e@10.42.0.12:30303"
      NETRESTRICT: "10.42.0.0/16"
      DISABLE_ZKEVM: "true"
      MAX_BLOCK_GAS: 10000000  #10M
      MAX_BLOCKDATA_BYTES: 35000 #35 KBytes
      MAX_TXDATA_BYTES: 30000 #30 KBytes
      ZKGETH_LOWER_GAS_MARGIN_PERCENTS: 120
      ZKGETH_UPPER_GAS_MARGIN_PERCENTS: 300
    entrypoint: ""
    command: [ "sh", "/scripts/node.sh", "12345", "/genesis.json", "0x1", "0x1C9C380", "0x1" ]
    volumes:
      - ./config/geth/scripts:/scripts:ro
      - ./config/genesis/genesis.devnet.json:/genesis.json:ro
      - ./config/geth/geth-l2-node.key:/boot.key:ro
      - l2-node-data:/data
    networks:
      devnet:
        ipv4_address: 10.42.0.13

  traces-node:
    image: consensys/linea-besu-package:devnet-ceeabfa
    profiles: [ "nodes", "services" ]
    depends_on:
      sequencer:
        condition: service_healthy
    ports:
      - "8745:8545"
      - "8746:8546"
      - "8750:8550"
      - "8751:8548"
      - "30308:30303"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /tmp/pid ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    restart: "no"
    environment:
      LOG4J_CONFIGURATION_FILE: /var/lib/besu/log4j.xml
      # possibly the "-Xms32g -Xss4m" can be reduced
      JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:-UseG1GC -XX:+UseZGC -Xmx80g -Xss128m
      SLACK_SHADOW_NODE_WEBHOOK_URL: "https://example.com"
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/config.toml \
        --static-nodes-file="/var/lib/besu/static-nodes.json" \
        --bootnodes="enode://94b0eebcac4ffa2946a038bcf3e3155db348945231947432cb5cf2611bfab3864f154387962bf90a7b52fbc0c58498d43a58e44d4ce00f8b7b6883733fffee4e@10.42.0.12:30303"
    volumes:
      - ./config/traces-node/config.toml:/var/lib/besu/config.toml:ro
      - ./config/traces-node/log4j.xml:/var/lib/besu/log4j.xml:ro
      - ./config/traces-node/static-nodes.json:/var/lib/besu/static-nodes.json
      - ./config/genesis/genesis.devnet.json:/var/lib/besu/genesis.json:ro
      - traces-node-data:/opt/besu
      - ./local.dev/data/traces/v2/conflated:/data/traces/v2/conflated:rw
    networks:
      devnet:
        ipv4_address: 10.42.0.15

  shomei-node:
    image: consensys/linea-besu-package:devnet-fc27c01
    hostname: zkbesu-shomei
    container_name: zkbesu-shomei
    profiles: [ "nodes", "services" ]
    depends_on:
      sequencer:
        condition: service_healthy
    privileged: true
    user: root
    ports:
      - "8945:8545"
      - "8946:8546"
      - "8950:8550"
      - "30307:30303"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /tmp/pid ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    networks:
      devnet:
        ipv4_address: 10.42.0.14
    environment:
      LOG4J_CONFIGURATION_FILE: /var/lib/besu/log4j.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/config.toml \
        --genesis-file=/var/lib/besu/genesis.json \
        --plugin-shomei-http-host="10.42.0.16" \
        --plugin-shomei-http-port=8888 \
        --Xbonsai-limit-trie-logs-enabled=false \
        --bootnodes="enode://94b0eebcac4ffa2946a038bcf3e3155db348945231947432cb5cf2611bfab3864f154387962bf90a7b52fbc0c58498d43a58e44d4ce00f8b7b6883733fffee4e@10.42.0.12:30303"
    volumes:
      - ./config/shomei-node/config.toml:/var/lib/besu/config.toml:ro
      - ./config/shomei-node/log4j.xml:/var/lib/besu/log4j.xml:ro
      - ./config/genesis/genesis.devnet.json:/var/lib/besu/genesis.json:ro
      - shomei-node-data:/opt/besu

  shomei:
    image: consensys/linea-shomei:2.3.0
    profiles: [ "services" ]
    depends_on:
      - shomei-node
    privileged: true
    user: root
    ports:
      - "8998:8888"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /data/shomei/LOCK ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 60
    environment:
      LOG4J_CONFIGURATION_FILE: /log4j.xml
    command:
      - --besu-rpc-http-host=10.42.0.14
      - --besu-rpc-http-port=8545
      - --rpc-http-host=10.42.0.16
      - --rpc-http-host-allow-list=*
      - --rpc-http-port=8888
      - --min-confirmations-before-importing=1 # at least 1, 0 leads to memory leak
      - --trace-start-block-number=0
      - --data-path=/data/shomei
    volumes:
      - ./local.dev:/data
      - ./config/shomei/log4j.xml:/log4j.xml:ro
    networks:
      devnet:
        ipv4_address: 10.42.0.16

  shomei-frontend:
    image: consensys/linea-shomei:2.3.0
    hostname: shomei-frontend
    container_name: shomei-frontend
    profiles: [ "services" ]
    depends_on:
      - shomei-node
    privileged: true
    user: root
    restart: always
    ports:
      - "8889:8888"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"[ -f /data/shomei/LOCK ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 60
    environment:
      LOG4J_CONFIGURATION_FILE: /log4j.xml
    command:
      - --besu-rpc-http-host=10.42.0.14
      - --besu-rpc-http-port=8545
      - --rpc-http-host=10.42.0.8
      - --rpc-http-host-allow-list=*
      - --rpc-http-port=8888
      - --min-confirmations-before-importing=0
      - --trace-start-block-number=0
      - --data-path=/data/shomei-frontend
      - --metrics-http-host=0.0.0.0
      - --metrics-http-port=9545
      - --enable-trace-generation=false
      - --enable-finalized-block-limit=true
      - --use-finalized-block-number=0
      - --use-finalized-block-hash=0x10ef85bec219af6c6f8176e64d6be44005a82a9b20235d0bc88281036a7fa952 #some unlikely hash
    volumes:
      - ./local.dev:/data
      - ./config/shomei/log4j.xml:/log4j.xml:ro
    networks:
      devnet:
        ipv4_address: 10.42.0.8

  coordinator:
    image: consensys/linea-coordinator:a5119c4
    platform: linux/amd64
    profiles: [ "services" ]
    depends_on:
      - postgres
      - traces-node
      - shomei-node
      - shomei-frontend
      - shomei
    ports:
      - "9545:9545"
    restart: on-failure
    command: [ 'java', '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005','-Dvertx.configurationFile=/var/lib/coordinator/vertx-options.json', '-Dlog4j2.configurationFile=/var/lib/coordinator/log4j2-dev.xml', '-jar', 'libs/coordinator.jar', '--traces-limits-v2', 'config/traces-limits-v2.toml', '--smart-contract-errors', 'config/smart-contract-errors.toml', '--gas-price-cap-time-of-day-multipliers', 'config/gas-price-cap-time-of-day-multipliers.toml', 'config/coordinator-docker.config.toml', 'config/coordinator-docker-traces-v2-override.config.toml' ]
    volumes:
      - ./config/coordinator/traces-limits-v2.toml:/opt/consensys/linea/coordinator/config/traces-limits-v2.toml:ro
      - ./config/coordinator/coordinator-docker-traces-v2-override.config.toml:/opt/consensys/linea/coordinator/config/coordinator-docker-traces-v2-override.config.toml:ro
      - ./config/coordinator/coordinator-docker.config.toml:/opt/consensys/linea/coordinator/config/coordinator-docker.config.toml:ro
      - ./config/smart-contract-errors.toml:/opt/consensys/linea/coordinator/config/smart-contract-errors.toml:ro
      - ./config/gas-price-cap-time-of-day-multipliers.toml:/opt/consensys/linea/coordinator/config/gas-price-cap-time-of-day-multipliers.toml:ro
      - ./config/coordinator/vertx-options.json:/var/lib/coordinator/vertx-options.json:ro
      - ./config/coordinator/log4j2-dev.xml:/var/lib/coordinator/log4j2-dev.xml:ro
      - ./local.dev/data:/data/
    networks:
      devnet:
        ipv4_address: 10.42.0.9

  postgres:
    image: postgres:14.5
    profiles: [ "services" ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-coordinator}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 120
    restart: unless-stopped
    volumes:
      - ./config/postgres/init:/docker-entrypoint-initdb.d/
      - ./config/postgres/conf/:/etc/postgresql/
      - ./local.dev/postgres:/var/lib/postgresql/data
    networks:
      - devnet

  web3signer:
    hostname: web3signer
    container_name: web3signer
    image: consensys/web3signer:23.3-jdk17
    profiles: [ "services" ]
    ports:
      - "9000:9000"
    command:
      - --key-store-path=/keyFiles/
      - --http-host-allowlist=*
      - eth1
    volumes:
      - ./config/web3signer/keyFiles/:/keyFiles/
    networks:
      - devnet

  prover-v3-full: # prover compatible with the traces from zkbesu
    container_name: prover
    image: consensys/linea-prover:cd7228ec # rebuild with MaxNbInstance4096: 2
    platform: linux/amd64
    profiles: [ "full-prover" ]
    working_dir: /linea-monorepo
    environment:
      GOMAXPROCS: 64
      GOMEMLIMIT: "1100GiB"
      CONFIG_FILE: "/opt/linea/prover/config.toml"
      WORKER_ID: prover-i1 # keep this prover- to mimic prod env prover-aggregation-91
    volumes:
      - ./local.dev/data:/data/
      - ./local.dev/prover/logs:/logs
      - ./config/prover/v3/prover-config-full.toml:/opt/linea/prover/config.toml:ro
      - ./prover-assets:/opt/linea/prover/prover-assets:ro
      - ./tmp.dev/prover-artefacts:/tmp/prover-artefacts
      - ./prover-assets/compressor_dict.bin:/linea-monorepo/prover/lib/compressor/compressor_dict.bin
    networks:
      devnet:
        ipv4_address: 10.42.0.18

  postman:
    container_name: postman
    hostname: postman
    image: consensys/linea-postman:cd7228e
    profiles: [ "services" ]
    platform: linux/amd64
    restart: on-failure
    depends_on:
      sequencer:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file: "./config/postman/env"
    networks:
      devnet:
        ipv4_address: 10.42.0.19

  transaction-exclusion-api:
    hostname: transaction-exclusion-api
    container_name: transaction-exclusion-api
    image: consensys/linea-transaction-exclusion-api:8749f92
    profiles: [ "services" ]
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8080"
    command: [ 'java', '-Dvertx.configurationFile=config/vertx-options.json', '-Dlog4j2.configurationFile=config/log4j2-dev.xml', '-jar', 'libs/transaction-exclusion-api.jar', 'config/transaction-exclusion-app-docker.config.toml', ]
    volumes:
      - ./config/transaction-exclusion-api/transaction-exclusion-app-docker.config.toml:/opt/consensys/linea/transaction-exclusion-api/config/transaction-exclusion-app-docker.config.toml:ro
      - ./config/transaction-exclusion-api/vertx-options.json:/opt/consensys/linea/transaction-exclusion-api/config/vertx-options.json:ro
      - ./config/transaction-exclusion-api/log4j2-dev.xml:/opt/consensys/linea/transaction-exclusion-api/config/log4j2-dev.xml:ro
      - ./local.dev:/data/
    networks:
      devnet:
        ipv4_address: 10.42.0.20


networks:
  devnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.42.0.0/16
          gateway: 10.42.0.1

volumes:
  sequencer-data:
  traces-node-data:
  shomei-node-data:
  l2-node-data:
