environment = "devnet"
version = "4.0.0"
assets_dir = "/opt/linea/prover/prover-assets"
log_level = 4

[controller]
retry_delays = [0, 1]

[execution]
prover_mode = "full"
requests_root_dir = "/data/prover/v3/execution"
conflated_traces_dir = "/"

[blob_decompression]
prover_mode = "full"
requests_root_dir = "/data/prover/v3/compression"
dict_path = "/opt/linea/prover/lib/compressor/compressor_dict.bin"

[public_input_interconnection]
max_nb_decompression = 20
max_nb_execution = 20
max_nb_circuits = 20
execution_max_nb_msg = 16
l2_msg_merkle_depth = 5
l2_msg_max_nb_merkle = 200

[aggregation]
prover_mode = "full"
num_proofs = [10, 20]
allowed_inputs = ["execution", "blob-decompression-v1"]
verifier_id = 1
requests_root_dir = "/data/prover/v3/aggregation"

[layer2]
chain_id = 12345
message_service_contract = "0x22A4913037A2079fada1b9BfBdc5C81c85781264"

[traces_limits]
ADD = 524288
BIN = 262144
BLAKE_MODEXP_DATA = 16384
BLOCK_DATA = 16384
BLOCK_HASH = 512
EC_DATA = 262144
EUC = 65536
EXP = 8192
EXT = 65536
GAS = 65536
HUB = 2097152
LOG_DATA = 65536
LOG_INFO = 65536
MMIO = 2097152
MMU = 4194304
MOD = 131072
MUL = 65536
MXP = 524288
OOB = 262144
RLP_ADDR = 8192
RLP_TXN = 524288
RLP_TXN_RCPT = 524288
ROM = 8388608
ROM_LEX = 8192
SHAKIRA_DATA = 32768
SHF = 65536
STP = 32768
TRM = 65536
TXN_DATA = 65536
WCP = 262144
BLOCK_KECCAK = 8192
BLOCK_L1_SIZE = 1000000
BLOCK_L2_L1_LOGS = 16
BLOCK_TRANSACTIONS = 2048
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS = 128
PRECOMPILE_SHA2_BLOCKS = 671
PRECOMPILE_RIPEMD_BLOCKS = 671
PRECOMPILE_MODEXP_EFFECTIVE_CALLS = 4
PRECOMPILE_ECADD_EFFECTIVE_CALLS = 16384
PRECOMPILE_ECMUL_EFFECTIVE_CALLS = 32
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS = 16
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS    = 64
PRECOMPILE_ECPAIRING_MILLER_LOOPS = 64
PRECOMPILE_BLAKE_EFFECTIVE_CALLS = 600
PRECOMPILE_BLAKE_ROUNDS = 600
BIN_REFERENCE_TABLE = 262144
SHF_REFERENCE_TABLE = 4096
INSTRUCTION_DECODER = 512
